baseURL = "https://weekly.meik2333.com/"
languageCode = "zh-cn"
title = "MeiK's blog"
publishDir = "docs"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
googleAnalytics = "UA-107784973-4"

[params]
  contributions = "post"
  author = "MeiK"
  github = "MeiK2333"
  description = "In solitude, where we are least alone."
  twitter = "MeiK2333"
  email = "meik2333@gmail.com"
  utterances = "MeiK2333/MeiK2333.github.io"
  rss = true
  location = "China"
  lastmod = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

